# Generated by Django 5.0.6 on 2025-02-18 15:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('code', models.TextField(validators=[django.core.validators.MaxLengthValidator(512)], verbose_name='код для вставки')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='аттрибут title')),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
                'ordering': ('order_number',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='videos_vide_content_6d1d17_idx')],
            },
        ),
    ]
