# Generated by Django 5.0.6 on 2025-02-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='заголовок'),
        ),
    ]
