# Generated by Django 5.0.6 on 2025-02-19 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='code',
            field=models.TextField(help_text='Под видео "... Еще" -> Экспортировать -> Код для вставки.', validators=[django.core.validators.MaxLengthValidator(512)], verbose_name='код для вставки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Нигде не отображается, нужен, чтобы не запутаться.', max_length=255, verbose_name='заголовок'),
        ),
    ]
