# Generated by Django 5.0.6 on 2025-02-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_video_code_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='Под видео: "... Еще" -> Экспортировать -> Прямая ссылка. Пример: "https://vk.com/video-111111111_999999999".', max_length=255, verbose_name='ссылка'),
        ),
    ]
