# Generated by Django 5.0.2 on 2024-02-20 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='заголовок')),
                ('meta_description', models.CharField(max_length=160, verbose_name='мета описание')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('company_name', models.CharField(max_length=80, verbose_name='название компании')),
                ('inn', models.CharField(blank=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=9, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='КПП')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес')),
                ('phone_retail', models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон (розница)')),
                ('phone_wholesale', models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон (опт)')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('work_schedule', models.CharField(blank=True, max_length=50, null=True, verbose_name='график работы')),
                ('map', models.TextField(blank=True, null=True, verbose_name='карта')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
