# Generated by Django 5.0.6 on 2025-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='work_schedule',
            field=models.CharField(choices=[('CLOSED', 'Закрыт до весны'), ('NORMAL', 'Пн-Сб: 09:00-19:00, Вс: выходной'), ('SHORT', 'Пн-Сб: 09:00-18:00, Вс: выходной')], default='NORMAL', max_length=50, unique=True, verbose_name='график работы'),
        ),
    ]
