# Generated by Django 5.0.6 on 2025-02-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_work_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(max_length=200, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_retail',
            field=models.CharField(max_length=20, verbose_name='телефон (розница)'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_wholesale',
            field=models.CharField(max_length=20, verbose_name='телефон (опт)'),
        ),
    ]
