# Generated by Django 5.0.6 on 2025-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contacts_address_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='work_schedule',
            field=models.CharField(choices=[('CLOSED', 'Закрыт до весны'), ('NORMAL', 'Пн-Сб: 09:00-19:00, Вс: выходной'), ('SHORT', 'Пн-Сб: 09:00-18:00, Вс: выходной')], default='NORMAL', help_text='Так же изменится и в "шапке" сайта.', max_length=50, unique=True, verbose_name='график работы'),
        ),
    ]
