# Generated by Django 5.0.6 on 2025-02-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contacts_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CLOSED', 'Закрыт до весны'), ('NORMAL', 'Пн-Сб: 09:00-19:00, Вс: выходной'), ('SHORT', 'Пн-Сб: 09:00-18:00, Вс: выходной')], default='NORMAL', help_text='Так же изменится и в "шапке" сайта.', max_length=50, unique=True, verbose_name='график работы')),
            ],
            options={
                'verbose_name': 'график работы',
                'verbose_name_plural': 'график работы',
            },
        ),
    ]
