# Generated by Django 5.0.6 on 2025-02-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_workschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='work_schedule',
        ),
    ]
