# Generated by Django 5.0.6 on 2025-02-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_contacts_work_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'график работы*', 'verbose_name_plural': 'график работы'},
        ),
    ]
