# Generated by Django 5.0.6 on 2025-02-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_workschedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='name',
            field=models.CharField(choices=[('CLOSED', 'Закрыт до мая'), ('NORMAL', 'Пн-Сб: 09:00-19:00, Вс: выходной'), ('SHORT', 'Пн-Сб: 09:00-18:00, Вс: выходной')], default='NORMAL', max_length=50, unique=True, verbose_name='график работы'),
        ),
    ]
