# Generated by Django 5.0.2 on 2024-02-20 18:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BOOK', 'Книги'), ('RELATED', 'Сопутствующие товары')], default='FRU', max_length=7, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория товара',
                'verbose_name_plural': 'категории товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='заголовок')),
                ('meta_description', models.CharField(max_length=160, verbose_name='мета описание')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('short_description', models.CharField(max_length=250, verbose_name='короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('features', models.CharField(blank=True, max_length=250, verbose_name='особенности')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.otherproductcategory', verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OtherProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена, руб')),
                ('property', models.CharField(blank=True, max_length=150, verbose_name='параметры')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.otherproduct', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
                'ordering': ('price',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='otherproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='other_other_search__1ae0d2_gin'),
        ),
        migrations.AddIndex(
            model_name='otherproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='trgm_otherproduct_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
