# Generated by Django 5.0.1 on 2024-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherproductprice',
            name='property',
            field=models.CharField(max_length=150, verbose_name='параметры'),
        ),
    ]
