# Generated by Django 5.0.1 on 2024-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_rename_property_otherproductprice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherproductprice',
            name='name',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
    ]
