# Generated by Django 5.0.1 on 2024-03-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decproduct',
            name='inflorescence',
            field=models.CharField(blank=True, max_length=250, verbose_name='соцветия'),
        ),
    ]
