# Generated by Django 5.0.1 on 2024-02-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decspecies',
            options={'ordering': ('name',), 'verbose_name': 'вид лиственных растений', 'verbose_name_plural': 'виды лиственных растений'},
        ),
    ]
