# Generated by Django 5.0.1 on 2024-02-27 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0002_alter_decspecies_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='decproductprice',
            name='trunk_diameter',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='диаметр ствола, см'),
        ),
        migrations.AlterField(
            model_name='decproduct',
            name='flower_size',
            field=models.CharField(blank=True, help_text='Можно вводить цифры, от, до, "-". Например: 5, 5-10, от 5, до 5.', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='размер цветка, см'),
        ),
        migrations.AlterField(
            model_name='decproduct',
            name='inflorescence_size',
            field=models.CharField(blank=True, help_text='Можно вводить цифры, от, до, "-". Например: 5, 5-10, от 5, до 5.', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='размер соцветия, см'),
        ),
        migrations.AlterField(
            model_name='decproductprice',
            name='height',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='высота, см'),
        ),
        migrations.AlterField(
            model_name='decproductprice',
            name='shtamb',
            field=models.CharField(blank=True, help_text='Ветвление на стволе начинается c указанной высоты, см.', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='штамб, см'),
        ),
        migrations.AlterField(
            model_name='decproductprice',
            name='width',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='ширина, см'),
        ),
    ]
