# Generated by Django 5.0.1 on 2024-02-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0002_alter_decspecies_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='decspecies',
            unique_together=set(),
        ),
    ]
