# Generated by Django 5.0.1 on 2024-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0003_alter_decspecies_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='decproduct',
            name='shelter_winter',
            field=models.CharField(blank=True, max_length=50, verbose_name='укрытие на зиму'),
        ),
    ]
