# Generated by Django 5.0.1 on 2024-03-31 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0003_decproductprice_bush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='deciduous.decproduct', verbose_name='растение'),
        ),
    ]
