# Generated by Django 5.0.6 on 2024-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0004_alter_decproductprice_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='decproductprice',
            name='height_from',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='высота от, см'),
        ),
        migrations.AddField(
            model_name='decproductprice',
            name='height_to',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='высота до, см'),
        ),
        migrations.AddField(
            model_name='decproductprice',
            name='width_from',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='ширина от, см'),
        ),
        migrations.AddField(
            model_name='decproductprice',
            name='width_to',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='ширина до, см'),
        ),
    ]
