# Generated by Django 5.0.1 on 2024-03-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0005_alter_decproduct_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='decproduct',
            name='crown',
            field=models.CharField(blank=True, max_length=250, verbose_name='крона'),
        ),
    ]
