# Generated by Django 5.0.6 on 2024-05-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0006_auto_20240516_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decproductprice',
            name='height',
        ),
        migrations.RemoveField(
            model_name='decproductprice',
            name='width',
        ),
    ]
