# Generated by Django 5.0.6 on 2025-02-07 06:20

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deciduous', '0010_decproduct_name_trans_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='decproductprice',
            name='planting_year',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^[0-9+]+$', 'Можно вводить цифры'), common.validators.YearStringValidator], verbose_name='год посадки'),
        ),
    ]
