# Generated by Django 5.0.1 on 2024-03-22 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        ('roses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roseproductprice',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plantpricecontainer', verbose_name='контейнер'),
        ),
    ]
