# Generated by Django 5.0.1 on 2024-02-27 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roseproduct',
            name='flower_size',
            field=models.CharField(blank=True, help_text='Можно вводить цифры, от, до, "-". Например: 5, 5-10, от 5, до 5.', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='размер цветка, см'),
        ),
        migrations.AlterField(
            model_name='roseproduct',
            name='quantity_on_stem',
            field=models.CharField(blank=True, help_text='Можно вводить цифры, "-" и "+"', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='количество на стебле'),
        ),
    ]
