# Generated by Django 5.0.1 on 2024-02-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roseproduct',
            name='features',
        ),
    ]
