# Generated by Django 5.0.1 on 2024-03-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roses', '0002_alter_roseproductprice_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roseproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='roses.roseproduct', verbose_name='роза'),
        ),
    ]
