# Generated by Django 5.0.1 on 2024-03-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roses', '0002_remove_roseproduct_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roseproduct',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=1, verbose_name='показывать?'),
        ),
    ]
