# Generated by Django 5.0.1 on 2024-02-27 11:36

import django.core.validators
import pricelist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(max_length=140, upload_to=pricelist.models.get_filepath, validators=[django.core.validators.FileExtensionValidator(('xlsx',))], verbose_name='путь к файлу')),
            ],
            options={
                'verbose_name': 'загрузить прайс-лист',
                'verbose_name_plural': 'загрузить прайс-лист',
            },
        ),
    ]
