# Generated by Django 5.0.6 on 2025-02-25 20:38

import django.core.validators
import django.utils.timezone
import pricelist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='head_title',
            field=models.CharField(default='', max_length=80, verbose_name='заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=1, verbose_name='показывать?'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='meta_description',
            field=models.CharField(default='', max_length=160, verbose_name='мета описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='name',
            field=models.CharField(default='', max_length=80, unique=True, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='slug',
            field=models.SlugField(default='price-list', max_length=80, unique=True, verbose_name='слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='file_path',
            field=models.FileField(max_length=140, upload_to=pricelist.models.get_filepath, validators=[django.core.validators.FileExtensionValidator(('xlsx', 'xls', 'pdf'))], verbose_name='путь к файлу'),
        ),
    ]
