# Generated by Django 5.0.6 on 2025-02-26 07:20

import django.core.validators
import pricelist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_pricelist_created_at_pricelist_head_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='file_path',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=pricelist.models.get_filepath, validators=[django.core.validators.FileExtensionValidator(('xlsx', 'xls', 'pdf'))], verbose_name='путь к файлу'),
        ),
    ]
