# Generated by Django 5.0.6 on 2025-02-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_alter_pricelist_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
    ]
