# Generated by Django 5.0.6 on 2025-02-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0004_pricelist_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='head_title',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='updated_at',
        ),
    ]
