# Generated by Django 5.0.6 on 2025-02-27 08:04

import pricelist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0005_remove_pricelist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='arc_path',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=pricelist.models.get_filepath, verbose_name='путь к заархивированному файлу'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='arc_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='размер файла, Б'),
        ),
    ]
