# Generated by Django 5.0.6 on 2025-02-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0006_pricelist_arc_path_pricelist_arc_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='arc_size',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='размер файла, Б'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='размер файла, Б'),
        ),
    ]
