# Generated by Django 5.0.6 on 2025-02-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0007_alter_pricelist_arc_size_alter_pricelist_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='arc_size',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='file_size',
        ),
    ]
