# Generated by Django 5.0.6 on 2025-02-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0008_remove_pricelist_arc_size_remove_pricelist_file_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'загрузить*', 'verbose_name_plural': 'загрузить'},
        ),
    ]
