# Generated by Django 5.0.1 on 2024-02-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='user agent'),
        ),
    ]
