# Generated by Django 5.0.1 on 2024-03-08 19:07

import django.db.models.deletion
import easy_thumbnails.fields
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('path', easy_thumbnails.fields.ThumbnailerImageField(max_length=250, upload_to=images.models.get_image_path, verbose_name='Путь к картинке')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='аттрибут title')),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'картинка',
                'verbose_name_plural': 'картинки',
                'ordering': ('order_number',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='images_imag_content_0cb5ba_idx')],
            },
        ),
    ]
