# Generated by Django 5.0.1 on 2024-03-08 19:00

import easy_thumbnails.fields
import images.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=200, upload_to=images.models.get_image_path, verbose_name='Путь к картинке'),
        ),
    ]
