# Generated by Django 5.0.1 on 2024-03-15 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perennials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perproduct',
            name='flowering_period',
            field=models.CharField(blank=True, help_text='Можно вводить только римские цифры и "-". Например: IV, IV-VI.', max_length=9, validators=[django.core.validators.RegexValidator('(IX|IV|V?I{0,3}|\\-)', 'Можно вводить только римские цифры и "-"')], verbose_name='период цветения'),
        ),
    ]
