# Generated by Django 5.0.1 on 2024-02-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perennials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perspecies',
            options={'ordering': ('name',), 'verbose_name': 'вид многолетних растений', 'verbose_name_plural': 'виды многолетних растений'},
        ),
    ]
