# Generated by Django 5.0.1 on 2024-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perennials', '0002_alter_perproduct_flowering_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='perproduct',
            name='shelter_winter',
            field=models.CharField(blank=True, max_length=50, verbose_name='укрытие на зиму'),
        ),
    ]
