# Generated by Django 5.0.1 on 2024-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perennials', '0003_perproduct_shelter_winter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerProductFlowering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'цветение',
                'verbose_name_plural': 'цветение',
            },
        ),
        migrations.RemoveField(
            model_name='perproduct',
            name='flowering',
        ),
        migrations.AddField(
            model_name='perproduct',
            name='flowering',
            field=models.ManyToManyField(blank=True, related_name='+', to='perennials.perproductflowering', verbose_name='цветение'),
        ),
    ]
