# Generated by Django 5.0.1 on 2024-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perennials', '0004_perproductflowering_remove_perproduct_flowering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perproductprice',
            name='planting_year',
            field=models.CharField(blank=True, max_length=4, verbose_name='год посадки'),
        ),
    ]
