# Generated by Django 5.0.1 on 2024-03-31 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perennials', '0005_perproductprice_planting_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='perennials.perproduct', verbose_name='растение'),
        ),
    ]
