# Generated by Django 5.0.6 on 2024-05-17 06:08

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perennials', '0006_alter_perproductprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perproductprice',
            name='planting_year',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^[0-9+]+$', 'Можно вводить цифры'), common.validators.YearStringValidator], verbose_name='год посадки'),
        ),
    ]
