# Generated by Django 5.0.1 on 2024-02-27 11:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConiferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=80, verbose_name='заголовок')),
                ('meta_description', models.CharField(max_length=160, verbose_name='мета описание')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('short_description', models.CharField(max_length=250, verbose_name='короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('features', models.CharField(blank=True, max_length=250, verbose_name='особенности')),
                ('scientific_name', models.CharField(blank=True, max_length=100, verbose_name='научное название')),
                ('height', models.CharField(blank=True, help_text='Можно вводить цифры, от, до, м, см, "-" и ",". Например: 0,5 м, 0,5-1 м, от 0,5 м, до 0,5 м', max_length=10, validators=[django.core.validators.RegexValidator('^((от|до)[\\s])?\\d{1,3}(\\,\\d{1,3})?(\\-?\\d{1,3}(\\,\\d{1,3})?)?([\\s](м|см))?$', 'Можно вводить цифры, от, до, м, см, "-" и ","')], verbose_name='высота взрослого растения')),
                ('width', models.CharField(blank=True, help_text='Можно вводить цифры, от, до, м, см, "-"  и ",". Например: 0,5 м, 0,5-1 м, от 0,5 м, до 0,5 м', max_length=10, validators=[django.core.validators.RegexValidator('^((от|до)[\\s])?\\d{1,3}(\\,\\d{1,3})?(\\-?\\d{1,3}(\\,\\d{1,3})?)?([\\s](м|см))?$', 'Можно вводить цифры, от, до, м, см, "-" и ","')], verbose_name='ширина взрослого растения')),
                ('needles', models.CharField(blank=True, max_length=250, verbose_name='хвоя')),
                ('height10', models.CharField(blank=True, help_text='Можно вводить цифры, от, до, м, см, "-" и ","', max_length=10, validators=[django.core.validators.RegexValidator('^((от|до)[\\s])?\\d{1,3}(\\,\\d{1,3})?(\\-?\\d{1,3}(\\,\\d{1,3})?)?([\\s](м|см))?$', 'Можно вводить цифры, от, до, м, см, "-" и ","')], verbose_name='высота в 10 лет')),
                ('width10', models.CharField(blank=True, help_text='Можно вводить цифры, от, до, м, см, "-" и ","', max_length=10, validators=[django.core.validators.RegexValidator('^((от|до)[\\s])?\\d{1,3}(\\,\\d{1,3})?(\\-?\\d{1,3}(\\,\\d{1,3})?)?([\\s](м|см))?$', 'Можно вводить цифры, от, до, м, см, "-" и ","')], verbose_name='ширина в 10 лет')),
                ('height1', models.CharField(blank=True, help_text='Можно вводить цифры, от, до, м, см, "-" и ","', max_length=10, validators=[django.core.validators.RegexValidator('^((от|до)[\\s])?\\d{1,3}(\\,\\d{1,3})?(\\-?\\d{1,3}(\\,\\d{1,3})?)?([\\s](м|см))?$', 'Можно вводить цифры, от, до, м, см, "-" и ","')], verbose_name='годовой прирост в высоту')),
                ('width1', models.CharField(blank=True, help_text='Можно вводить цифры, от, до, м, см, "-" и ","', max_length=10, validators=[django.core.validators.RegexValidator('^((от|до)[\\s])?\\d{1,3}(\\,\\d{1,3})?(\\-?\\d{1,3}(\\,\\d{1,3})?)?([\\s](м|см))?$', 'Можно вводить цифры, от, до, м, см, "-" и ","')], verbose_name='годовой прирост в ширину')),
                ('shelter', models.CharField(blank=True, max_length=50, verbose_name='укрытие')),
                ('winter_zone', models.CharField(blank=True, max_length=30, verbose_name='зона зимостойкости в градусах')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('advantages', models.ManyToManyField(blank=True, related_name='+', to='plants.plantadvantage', verbose_name='достоинства')),
                ('planting', models.ManyToManyField(blank=True, related_name='+', to='plants.plantplanting', verbose_name='место посадки')),
            ],
            options={
                'verbose_name': 'хвойное растение',
                'verbose_name_plural': 'хвойные растения',
                'ordering': ('name', 'species'),
            },
        ),
        migrations.CreateModel(
            name='ConiferProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена, руб')),
                ('height', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='высота, см')),
                ('width', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='ширина, см')),
                ('trunk_diameter', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='диаметр ствола, см')),
                ('shtamb', models.CharField(blank=True, help_text='Ветвление на стволе начинается c указанной высоты, см.', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='штамб, см')),
                ('extra', models.BooleanField(default=False, help_text='Ухоженные растения.', verbose_name='экстра')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plantpricecontainer', verbose_name='контейнер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conifers.coniferproduct', verbose_name='растение')),
                ('rs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plantpricerootsystem', verbose_name='корневая система')),
            ],
            options={
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
                'ordering': ('price',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConiferSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Классификация растений: Отдел \\ Род \\ Вид. Пример: Хвойные \\ Ель \\ Ель канадская.', max_length=100, unique=True, verbose_name='вид')),
                ('genus', models.ForeignKey(help_text='Классификация растений: Отдел \\ Род. Пример: Хвойные \\ Ель.', on_delete=django.db.models.deletion.CASCADE, to='plants.plantgenus', verbose_name='род')),
            ],
            options={
                'verbose_name': 'вид хвойных растений',
                'verbose_name_plural': 'виды хвойных растений',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coniferproduct',
            name='species',
            field=models.ForeignKey(help_text='Классификация растений: Отдел \\ Род \\ Вид. Пример: Хвойные \\ Ель \\ Ель канадская.', on_delete=django.db.models.deletion.CASCADE, to='conifers.coniferspecies', verbose_name='вид'),
        ),
        migrations.AddIndex(
            model_name='coniferproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='conifers_co_search__ea1927_gin'),
        ),
        migrations.AddIndex(
            model_name='coniferproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='trgm_coniferproduct_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
