# Generated by Django 5.0.1 on 2024-03-31 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coniferproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='conifers.coniferproduct', verbose_name='растение'),
        ),
    ]
