# Generated by Django 5.0.1 on 2024-02-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coniferproductprice',
            name='trunk_diameter',
        ),
    ]
