# Generated by Django 5.0.1 on 2024-02-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coniferspecies',
            options={'ordering': ('name',), 'verbose_name': 'вид хвойных растений', 'verbose_name_plural': 'виды хвойных растений'},
        ),
    ]
