# Generated by Django 5.0.1 on 2024-04-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0002_alter_coniferproductprice_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coniferproduct',
            old_name='shelter_winter',
            new_name='shelter',
        ),
    ]
