# Generated by Django 5.0.1 on 2024-02-27 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0002_alter_coniferspecies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coniferproductprice',
            name='height',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='высота, см'),
        ),
        migrations.AlterField(
            model_name='coniferproductprice',
            name='shtamb',
            field=models.CharField(blank=True, help_text='Ветвление на стволе начинается c указанной высоты, см.', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='штамб, см'),
        ),
        migrations.AlterField(
            model_name='coniferproductprice',
            name='width',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='ширина, см'),
        ),
    ]
