# Generated by Django 5.0.1 on 2024-02-27 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0003_alter_coniferproductprice_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coniferproductprice',
            name='trunk_diameter',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='диаметр ствола, см'),
        ),
    ]
