# Generated by Django 5.0.1 on 2024-02-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0003_alter_coniferspecies_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coniferspecies',
            unique_together=set(),
        ),
    ]
