# Generated by Django 5.0.1 on 2024-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0003_rename_shelter_winter_coniferproduct_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coniferproduct',
            name='shelter',
            field=models.CharField(blank=True, max_length=50, verbose_name='укрытие'),
        ),
    ]
