# Generated by Django 5.0.1 on 2024-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0004_alter_coniferproduct_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='coniferproductprice',
            name='height_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='высота от, см'),
        ),
        migrations.AddField(
            model_name='coniferproductprice',
            name='height_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='высота до, см'),
        ),
        migrations.AddField(
            model_name='coniferproductprice',
            name='width_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ширина от, см'),
        ),
        migrations.AddField(
            model_name='coniferproductprice',
            name='width_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ширина до, см'),
        ),
    ]
