# Generated by Django 5.0.1 on 2024-03-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0005_alter_coniferproduct_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coniferproduct',
            old_name='shelter',
            new_name='shelter_winter',
        ),
    ]
