# Generated by Django 5.0.1 on 2024-05-02 14:50

from django.db import migrations


def split_demensions(apps, schema_editor):
    model = apps.get_model("conifers", "ConiferProductPrice")

    for obj in model.objects.all():
        if obj.height:
            height_list = obj.height.split('-')

            if len(height_list) == 1:
                obj.height_from = height_list[0]
                obj.height_to = height_list[0]

            if len(height_list) == 2:
                obj.height_from = height_list[0]
                obj.height_to = height_list[1]

        if obj.width:
            width_list = obj.width.split('-')

            if len(width_list) == 1:
                obj.width_from = width_list[0]
                obj.width_to = width_list[0]

            if len(width_list) == 2:
                obj.width_from = width_list[0]
                obj.width_to = width_list[1]

        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0005_coniferproductprice_height_from_and_more'),
    ]

    operations = [
        migrations.RunPython(split_demensions),
    ]
