# Generated by Django 5.0.1 on 2024-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conifers', '0006_rename_shelter_coniferproduct_shelter_winter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coniferproduct',
            name='shelter_winter',
            field=models.CharField(blank=True, max_length=50, verbose_name='укрытие на зиму'),
        ),
    ]
