# Generated by Django 5.0.1 on 2024-02-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'достоинства',
                'verbose_name_plural': 'достоинства',
            },
        ),
        migrations.CreateModel(
            name='PlantDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FRU', 'Плодовые'), ('DEC', 'Лиственные'), ('PER', 'Mноголетние'), ('CON', 'Хвойные')], default='FRU', max_length=3, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'отдел растений',
                'verbose_name_plural': 'отделы растений',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlantPlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'место посадки',
                'verbose_name_plural': 'место посадки',
            },
        ),
        migrations.CreateModel(
            name='PlantPriceContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='название')),
                ('description', models.CharField(max_length=200, verbose_name='описание')),
                ('order_number', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='порядковый номер')),
            ],
            options={
                'verbose_name': 'контейнер',
                'verbose_name_plural': 'контейнеры',
                'ordering': ('order_number',),
            },
        ),
        migrations.CreateModel(
            name='PlantPriceRootSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, verbose_name='аббревиатура')),
                ('abbr_en', models.CharField(blank=True, max_length=10, verbose_name='аббревиатура на английском')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'корневая система',
                'verbose_name_plural': 'корневые системы',
                'ordering': ('abbr',),
            },
        ),
        migrations.CreateModel(
            name='PlantGenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Классификация растений: Отдел \\ Род. Пример: Хвойные \\ Ель.', max_length=100, unique=True, verbose_name='род')),
                ('division', models.ForeignKey(help_text='Классификация растений: Отдел. Пример: Хвойные.', on_delete=django.db.models.deletion.CASCADE, to='plants.plantdivision', verbose_name='отдел')),
            ],
            options={
                'verbose_name': 'род растений',
                'verbose_name_plural': 'рода растений',
                'ordering': ('name',),
            },
        ),
    ]
