# Generated by Django 5.0.1 on 2024-02-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantgenus',
            name='name',
            field=models.CharField(help_text='Классификация растений: Отдел \\ Род. Пример: Хвойные \\ Ель.', max_length=100, verbose_name='род'),
        ),
    ]
