# Generated by Django 5.0.6 on 2024-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantpricecontainer',
            name='description',
            field=models.CharField(help_text='Например: Горшок объемом 10 литров.', max_length=200, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='plantpricecontainer',
            name='order_number',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: P9-0.9, P15-0.15, C1-1, C10-10 и т.д.', max_digits=5, null=True, verbose_name='порядковый номер'),
        ),
    ]
