# Generated by Django 5.0.1 on 2024-02-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plantgenus_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantgenus',
            unique_together={('name', 'division')},
        ),
    ]
