# Generated by Django 5.0.1 on 2024-03-04 15:50

import easy_thumbnails.fields
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catalog', '0001_initial'), ('catalog', '0002_alter_catalog_image_path'), ('catalog', '0003_alter_catalog_options_catalog_order_number'), ('catalog', '0004_alter_catalog_options'), ('catalog', '0005_rename_catalog_catalogitem')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('url', models.CharField(max_length=250, verbose_name='url')),
                ('image_path', easy_thumbnails.fields.ThumbnailerImageField(max_length=200, upload_to=images.models.get_image_path, verbose_name='Путь к картинке')),
                ('order_number', models.PositiveSmallIntegerField(default=1, verbose_name='порядковый номер')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
                'ordering': ('order_number',),
            },
        ),
    ]
