# Generated by Django 5.0.1 on 2024-03-08 19:07

import easy_thumbnails.fields
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(db_index=True, default=1, verbose_name='показывать')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('url', models.CharField(max_length=250, verbose_name='url-адрес')),
                ('order_number', models.PositiveSmallIntegerField(verbose_name='порядковый номер')),
                ('image_path', easy_thumbnails.fields.ThumbnailerImageField(max_length=200, upload_to=images.models.get_image_path, verbose_name='Путь к картинке')),
                ('image_title', models.CharField(blank=True, max_length=200, verbose_name='аттрибут title картинки')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
                'ordering': ('order_number',),
            },
        ),
    ]
