# Generated by Django 5.0.1 on 2024-03-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_catalogitem_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='image_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='аттрибут title картинки'),
        ),
    ]
