# Generated by Django 5.0.1 on 2024-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_catalogitem_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='url',
            field=models.CharField(max_length=250, verbose_name='url-адрес'),
        ),
    ]
