# Generated by Django 5.0.1 on 2024-03-07 10:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_catalogitem_url'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='catalogitem',
            managers=[
                ('is_visible_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=1, verbose_name='показывать'),
        ),
    ]
