# Generated by Django 5.0.1 on 2024-03-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_catalogitem_managers_catalogitem_is_visible'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='catalogitem',
            managers=[
            ],
        ),
    ]
