# Generated by Django 5.0.1 on 2024-02-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruitspecies',
            options={'ordering': ('name',), 'verbose_name': 'вид плодовых растений', 'verbose_name_plural': 'виды плодовых растений'},
        ),
    ]
