# Generated by Django 5.0.1 on 2024-03-15 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitproduct',
            name='beginning_fruiting',
            field=models.CharField(blank=True, help_text='Можно вводить цифры, от, до, "-". Например: 5, 5-10, от 5, до 5.', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\+\\/дот, ]+$', 'Можно вводить цифры, "/", "-" и "+"')], verbose_name='начало плодоношения на год'),
        ),
    ]
