# Generated by Django 5.0.1 on 2024-03-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_fruitproduct_fruit_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitproduct',
            name='fruit_dimension',
            field=models.CharField(blank=True, max_length=7, verbose_name='Величина плодов'),
        ),
    ]
