# Generated by Django 5.0.1 on 2024-03-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0004_alter_fruitspecies_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitproduct',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=1, verbose_name='показывать?'),
        ),
    ]
