# Generated by Django 5.0.1 on 2024-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0005_alter_fruitproduct_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitproductpriceage',
            name='age',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-летка'), (2, '2-летка'), (3, '3-летка'), (4, '4-летка'), (5, '5-летка'), (6, '6-летка'), (7, '7-летка'), (8, '8-летка'), (9, '9-летка'), (10, '10-летка'), (11, '11-летка'), (12, '12-летка')], default=1, unique=True, verbose_name='возраст'),
        ),
    ]
