# Generated by Django 5.0.1 on 2024-03-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0007_fruitproductpricerootstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitproductpricerootstock',
            name='rootstock',
            field=models.PositiveSmallIntegerField(choices=[(1, 'полукарлик'), (2, 'семенной')], default=1, unique=True, verbose_name='подвой'),
        ),
    ]
