# Generated by Django 5.0.6 on 2024-05-17 08:02

from django.db import migrations


def split_demensions(apps, schema_editor):
    model = apps.get_model("fruits", "FruitProductPrice")

    for obj in model.objects.all():
        if obj.height:
            if obj.height.find('+') >= 0:
                height_list = obj.height.split('+')
                height_list = list(filter(None, height_list))
            elif obj.height.find('-') >= 0:
                height_list = obj.height.split('-')
            else:
                height_list = []
                height_list.insert(0, obj.height)
                height_list.insert(1, obj.height)

            if len(height_list) == 1:
                obj.height_from = height_list[0]

            if len(height_list) == 2:
                obj.height_from = height_list[0]
                obj.height_to = height_list[1]

        if obj.width:
            if obj.width.find('-') >= 0:
                width_list = obj.width.split('-')
            else:
                width_list = []
                width_list.insert(0, obj.width)
                width_list.insert(1, obj.width)

            if len(width_list) == 1:
                obj.width_from = width_list[0]

            if len(width_list) == 2:
                obj.width_from = width_list[0]
                obj.width_to = width_list[1]

        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0010_fruitproductprice_height_from_and_more'),
    ]

    operations = [
        migrations.RunPython(split_demensions),
    ]
