# Generated by Django 5.0.6 on 2024-05-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0013_alter_fruitproductprice_height_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitproduct',
            name='name_trans_words',
            field=models.CharField(blank=True, help_text='Перечисление слов через запятую. Например: если название "Alberta Globe", то: альберта, глоб, глоуб. Скрытое поле, предназначено для поиска.', max_length=100, verbose_name='перевод слов в названии'),
        ),
    ]
