# Generated by Django 5.0.6 on 2025-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0014_fruitproduct_name_trans_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitproductprice',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
