# Generated by Django 5.0.6 on 2025-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0015_fruitproductprice_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitproduct',
            name='fruit_dimension',
            field=models.CharField(blank=True, max_length=7, verbose_name='величина плодов'),
        ),
    ]
