# Generated by Django 5.0.6 on 2025-02-04 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявление',
            },
        ),
    ]
