# Generated by Django 5.0.1 on 2024-03-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_index_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='con_description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='index',
            name='con_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='index',
            name='con_short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='короткое описание'),
        ),
        migrations.AddField(
            model_name='index',
            name='con_visible',
            field=models.BooleanField(default=1, verbose_name='показывать?'),
        ),
        migrations.AddField(
            model_name='index',
            name='dec_description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='index',
            name='dec_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='index',
            name='dec_short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='короткое описание'),
        ),
        migrations.AddField(
            model_name='index',
            name='dec_visible',
            field=models.BooleanField(default=1, verbose_name='показывать?'),
        ),
        migrations.AddField(
            model_name='index',
            name='fru_description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='index',
            name='fru_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='index',
            name='fru_short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='короткое описание'),
        ),
        migrations.AddField(
            model_name='index',
            name='fru_visible',
            field=models.BooleanField(default=1, verbose_name='показывать?'),
        ),
        migrations.AddField(
            model_name='index',
            name='per_description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='index',
            name='per_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='index',
            name='per_short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='короткое описание'),
        ),
        migrations.AddField(
            model_name='index',
            name='per_visible',
            field=models.BooleanField(default=1, verbose_name='показывать?'),
        ),
    ]
