# Generated by Django 5.0.1 on 2024-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_index_con_description_index_con_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='about_us',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
