# Generated by Django 5.0.1 on 2024-03-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_index_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='about_us',
            new_name='description',
        ),
    ]
