# Generated by Django 5.0.1 on 2024-03-09 10:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('customer_first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('customer_last_name', models.CharField(blank=True, max_length=50, verbose_name='фамилия')),
                ('customer_email', models.EmailField(max_length=70, verbose_name='адрес электронной почты')),
                ('customer_phone_number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('customer_comment', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='комментарий к заказу')),
                ('confirm_code', models.CharField(default='-', max_length=4, verbose_name='код подтверждения заказа')),
                ('confirmed_by_email', models.BooleanField(blank=True, default=None, null=True, verbose_name='заказ подтвержден по электронной почте')),
                ('ip', models.CharField(blank=True, max_length=39, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('status_change_email', models.BooleanField(default=False, verbose_name='отправить письмо при смене статуса')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus', verbose_name='статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'заказанный товар',
                'verbose_name_plural': 'заказанные товары',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='orders_orde_content_9c040d_idx')],
            },
        ),
    ]
