# Generated by Django 5.0.1 on 2024-04-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirm_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed_by_email',
        ),
    ]
