# Generated by Django 5.0.6 on 2025-02-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_confirm_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_orders', models.CharField(choices=[('YES', 'Принимаются'), ('NO_UNTIL_APRIL', 'Прием закрыт до первых чисел апреля')], default='NORMAL', max_length=50, unique=True, verbose_name='Прием заказов')),
            ],
            options={
                'verbose_name': 'прием заказов',
                'verbose_name_plural': 'прием заказов',
            },
        ),
    ]
