# Generated by Django 5.0.6 on 2025-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_acceptingorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptingorders',
            name='accept_orders',
        ),
        migrations.AddField(
            model_name='acceptingorders',
            name='name',
            field=models.CharField(choices=[('YES', 'Принимаются'), ('NO_UNTIL_APRIL', 'Прием закрыт до первых чисел апреля')], default='YES', max_length=50, unique=True, verbose_name='Прием заказов'),
        ),
    ]
