# Generated by Django 5.0.6 on 2025-02-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_acceptingorders_accept_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptingorders',
            options={'verbose_name': 'прием заказов*', 'verbose_name_plural': 'прием заказов'},
        ),
    ]
