# Generated by Django 5.0.6 on 2025-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_acceptingorders_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptingorders',
            name='name',
            field=models.CharField(choices=[('ORDER', 'Принимаются заказы'), ('PRE_ORDER', 'Принимаются предзаказы'), ('CLOSE_UNTIL_APRIL', 'Не принимаются до первых чисел апреля')], default='ORDER', max_length=50, unique=True, verbose_name='Режим приема'),
        ),
    ]
