# Generated by Django 5.0.6 on 2024-10-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plantpricecontainer_description_and_more'),
        ('seedlings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedling',
            options={'ordering': ('name',), 'verbose_name': 'саженцы', 'verbose_name_plural': 'саженцы'},
        ),
        migrations.AlterUniqueTogether(
            name='seedling',
            unique_together={('name', 'division')},
        ),
    ]
