# Generated by Django 5.0.6 on 2024-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlings', '0002_alter_seedling_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedling',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=1, verbose_name='показывать?'),
        ),
    ]
