# Generated by Django 5.0.6 on 2025-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlings', '0003_seedling_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedling',
            name='url',
            field=models.CharField(help_text='Url-адрес страницы с ценами. Например: https://viride.spb.ru/catalog/conifers/el-kanadskaya-alberta-globe/', max_length=250, verbose_name='url-адрес'),
        ),
    ]
