# Generated by Django 5.0.6 on 2024-05-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_discount_description_discount_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
    ]
