# Generated by Django 5.0.6 on 2024-09-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_promotion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='price_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='новая цена, руб'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='price_old',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='старая цена, руб'),
        ),
    ]
