# Generated by Django 5.0.6 on 2024-09-25 15:48

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_discount_percent_alter_discount_price_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9+]+$', 'Можно вводить цифры'), common.validators.PercentValidator], verbose_name='скидка в процентах'),
        ),
    ]
